HW2 completed
TheJubadze/OtusGolangPro pull request #3
Opened 2024-04-19 10:09 UTC by TheJubadze

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-04-19 10:48 UTC, vladislavmass requested changes
Хорошее начало, но работа не проходит следующие тест кейсы которые должны привести к ошибки 
```
`aa\`, `aa\\33`
```

2024-04-19 20:21 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	for i, ch := range str {
За этот блок if идя по коду мы приводим руну к строке несколько раз. Лучше было бы сделать приведение 1 раз

2024-04-19 20:24 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +			if _, err := strconv.Atoi(string(ch)); err == nil || string(ch) == `\` {
Почему бы тут не использовать сравнение не со строкой а с руной. Руна занимает в памяти меньше места чем строка. А также почему мы везде используем символ вместо константы ? Что будет если мы решим что у нас теперб экранирует не слэш, а фигурная скобка? Нам предется менять код в 2 местах, хотя можно было бы просто поменять значение константы

2024-04-20 09:24 UTC, TheJubadze commented on hw02_unpack_string/unpack.go
> +	for i, ch := range str {
fixed

2024-04-20 09:24 UTC, TheJubadze commented on hw02_unpack_string/unpack.go
> +			if _, err := strconv.Atoi(string(ch)); err == nil || string(ch) == `\` {
fixed

2024-04-20 20:08 UTC, vladislavmass approved these changes
Работа стала лучше, хотя алгоритм все еще не очень оптимален

2024-04-21 05:39 UTC, merged