Hw04 lru cache
TheJubadze/OtusGolangPro pull request #5
Opened 2024-04-24 10:38 UTC by TheJubadze

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-04-24 11:26 UTC, vladislavmass requested changes

2024-04-24 11:26 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.front == i {
Предположим мы удаляем из списка единственный элемент. Он первый он же последний. В результате работы этого метода будет паника. Так как `i.Next=nil` а следующая строка сделает следующее `nil.Prev=nil`, а так как у `ni`l нет `Prev` то мы получим панику. И даже если бы тут не было паники, то после работы этого кода на единственно элементе l.back указывал бы на элемент который мы удалили

2024-04-24 11:26 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.back == i {
Тоже самое что и выше

2024-04-24 11:26 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	keys     map[*ListItem]Key
Эта мапа тут явно лишняя

2024-04-24 11:26 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	if cache.queue.Len() > cache.capacity {
Размер очереди не должен превышать капасити, а тут хоть и не на долго но размер очереди превышает капасити

2024-04-24 12:22 UTC, TheJubadze commented on hw04_lru_cache/cache.go
> +	keys     map[*ListItem]Key
Тоже так считаю, но что-то я никак не смог придумать, как без этого костыля сделать удаление ключа из мапы за `О(1)`. Была лишь идея итерироваться по мапе в поисках ключа по значению, но это уже `O(n)`. Может быть подскажете, как всё-таки обойтись без лишней мапы, сохранив сложность `О(1)`? Спасибо!

2024-04-24 12:23 UTC, TheJubadze commented on hw04_lru_cache/list.go
> +	if l.front == i {
Спасибо. Попраил, добавил тестов на этот кейс

2024-04-24 12:26 UTC, TheJubadze commented on hw04_lru_cache/cache.go
> +	if cache.queue.Len() > cache.capacity {
fixed

2024-04-24 12:29 UTC, vladislavmass requested changes

2024-04-24 12:29 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	keys     map[*ListItem]Key
В самом задание есть подсказка как это сделать. `Элемент кэша хранит в себе ключ, по которому он лежит в словаре, и само значение.`

2024-04-24 21:19 UTC, vladislavmass requested changes

2024-04-24 21:19 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.back == nil {
Это и предыдущее условие взаимоисключающие, нет валидной ситуации когда front не nil, а  back nil

2024-04-24 21:19 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.front == nil {
Это и предыдущее условие взаимоисключающие, нет валидной ситуации когда front не nil, а back nil

2024-04-24 21:19 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +func (cache *lruCache) String() string {
Данный код не потокобезопасен

2024-04-24 21:19 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	if cache.queue.Len()+1 > cache.capacity {
+1 можно заменит на больше или ровно

2024-04-24 21:19 UTC, vladislavmass commented on hw04_lru_cache/cache_test.go
>  func TestCacheMultithreading(t *testing.T) {
Очень большая просьба не вносить правки в наши тесты

2024-04-25 07:05 UTC, TheJubadze commented on hw04_lru_cache/list.go
> +	if l.back == nil {
изменил логику метода

2024-04-25 07:06 UTC, TheJubadze commented on hw04_lru_cache/list.go
> +	if l.front == nil {
изменил логику метода

2024-04-25 07:06 UTC, TheJubadze commented on hw04_lru_cache/cache.go
> +func (cache *lruCache) String() string {
добавил локи

2024-04-25 07:06 UTC, TheJubadze commented on hw04_lru_cache/cache.go
> +	if cache.queue.Len()+1 > cache.capacity {
done

2024-04-25 07:06 UTC, TheJubadze commented on hw04_lru_cache/cache_test.go
>  func TestCacheMultithreading(t *testing.T) {
Понял, учту на будущее, спасибо

2024-04-25 08:02 UTC, vladislavmass approved these changes

2024-04-25 08:04 UTC, merged